name: Continuous Integration
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # https://github.com/marketplace/actions/shellcheck
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
